// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace TrimmedTodo.Console.EfCore.Sqlite.CompiledModels
{
    public partial class TodoDbModel
    {
        partial void Initialize()
        {
            var todo = TodoEntityType.Create(this);

            TodoEntityType.CreateAnnotations(todo);

            AddAnnotation("ProductVersion", "7.0.0-rc.2.22472.11");
        }
    }
}
