// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace TrimmedTodo.MinimalApi.EfCore.Sqlite.CompiledModels
{
    [DbContext(typeof(TodoDb))]
    public partial class TodoDbModel : RuntimeModel
    {
        static TodoDbModel()
        {
            var model = new TodoDbModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static TodoDbModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
